import chalk from "chalk";
import { checkIfDirectoryExists, createDirectory, createFileName, createFilePath, writeFile } from "~lib/utils/namesAndDirectoryHelper";
import { Guide } from "~types/guide";

const getColor = (color: string) => {
	switch (color) {
		case "red":
			return chalk.red;
		case "green":
			return chalk.green;
		case "yellow":
			return chalk.yellow;
		case "blue":
			return chalk.blue;
		default:
			return chalk.white;
	}
};

interface GuideDetails {
	fileName: string;
	convertedGuide: string;
	comment: string;
}

const convertGuide = (guide: Guide, transformer: Function, extension: string, prefix: string, color: string) => {
	const { name } = guide;
	const fileName = createFileName(name, extension, false, prefix).toLocaleLowerCase().replace(/\s+/g, "-");
	const convertedGuide = transformer(guide);

	const date = new Date().toLocaleDateString();
	const comment = `// * This file was generated on ${date} by the Tidal Design System.\n// * Do not edit this file directly.\n// * Instead, edit the source file and run the build script again.`;

	return { fileName, convertedGuide, comment, color, extension };
};

const writeGuideToFile = async ({ fileName, convertedGuide, comment, color, extension }: GuideDetails & { color: string; extension: string }) => {
	const filePathDefault = createFilePath(`guides/${extension}`, "");

	if (!(await checkIfDirectoryExists(filePathDefault))) {
		await createDirectory(filePathDefault);
	}

	console.log(getColor(color)(`Writing ${fileName} to ${extension}...`));

	writeFile(filePathDefault, fileName, `${comment}\n\n${convertedGuide}`);
};

const convertGuides = async (guides: Guide[], transformer: Function, extension: string, prefix: string, color: string) => {
	console.log(getColor(color)(`Converting guides to ${extension}...`));

	for (const guide of guides) {
		const convertedGuide = convertGuide(guide, transformer, extension, prefix, color);
		await writeGuideToFile(convertedGuide);
	}

	console.log(getColor(color)(`Finished converting guides to ${extension}!`));
};

export default convertGuides;
