import chalk from "chalk";
import { checkIfDirectoryExists, createDirectory, createFileName, createFilePath, writeFile } from "~lib/utils/namesAndDirectoryHelper";
import { ComponentGroup } from "~types/component";

const getColor = (color: string) => {
	switch (color) {
		case "red":
			return chalk.red;
		case "green":
			return chalk.green;
		case "magenta":
			return chalk.magenta;
		case "yellow":
			return chalk.yellow;
		case "blue":
			return chalk.blue;
		default:
			return chalk.white;
	}
};

interface GuideDetails {
	fileName: string;
	convertedGuide: string;
	comment: string;
}

const convertComponentGroup = (group: ComponentGroup, transformer: Function, extension: string, prefix: string, color: string) => {
	const { name } = group;
	const fileName = createFileName(name, extension, false, prefix).toLocaleLowerCase().replace(/\s+/g, "-");
	const convertedGuide = transformer(group);

	const date = new Date().toLocaleDateString();
	const comment = `// * This file was generated on ${date} by the Tidal Design System.\n// * Do not edit this file directly.\n// * Instead, edit the source file and run the build script again.`;

	return { fileName, convertedGuide, comment, color, extension };
};

const writeGuideToFile = async ({ fileName, convertedGuide, comment, color, extension }: GuideDetails & { color: string; extension: string }) => {
	const filePathDefault = createFilePath(`guides/${extension}`, "");

	if (!(await checkIfDirectoryExists(filePathDefault))) {
		await createDirectory(filePathDefault);
	}

	console.log(getColor(color)(`Writing ${fileName} to ${extension}...`));

	writeFile(filePathDefault, fileName, `${comment}\n\n${convertedGuide}`);
};

const convertComponents = async (componentGroups: ComponentGroup[], transformer: Function, extension: string, prefix: string, color: string) => {
	console.log(getColor(color)(`Converting guides to ${extension}...`));

	for (const group of componentGroups) {
		const convertedGuide = convertComponentGroup(group, transformer, extension, prefix, color);
		await writeGuideToFile(convertedGuide);
	}

	console.log(getColor(color)(`Finished converting guides to ${extension}!`));
};

export default convertComponents;
